language:
  - generic

services:
  - docker

before_install:
  - docker build -f ./dockerfile -t dangawne/Fdata_api .

before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"

deploy:
  provider: script
  script: docker image push dangawne/Fdata_api
  on:
    branch: main
