language:
  - generic

services:
  - docker

before_install:
  - docker build -f ./dockerfile -t dangawne/sp500_api .

before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"

deploy:
  provider: script
  script: docker image push dangawne/sp500_api
  on:
    branch: main
