# Start from the miniconda image
FROM dangawne/ubuntu_miniconda3x

# Copy the source code into the docker container
COPY ./app /app

# Create the conda environment
WORKDIR /app
RUN conda env create --file ./envs/env_flask.yml
#RUN conda env update --name mlflow-env --file ./model/conda.yaml

# Activate the environment and run the server
# This is a bit tricky. See: https://stackoverflow.com/questions/55123637/activate-conda-environment-in-docker
#ENTRYPOINT ["conda", "run", "-n", "api-env", "python", "<app name>"]

# To build, type docker build -f ./dockerfile_gruserver -t dangawne/energy_gru .
# docker run -p 6000:6000 dangawne/sp500_api